---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-winesapos-repo
  namespace: winesapos-repo
  labels:
    app: winesapos-repo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
