---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-winesapos-repo
  namespace: winesapos-repo
  labels:
    app: winesapos-repo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: winesapos-repo
  template:
    metadata:
      labels:
        app: winesapos-repo
    spec:
      containers:
        - name: nginx
          image: nginx:1.21.6
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              memory: 4Gi
            requests:
              memory: 256Mi
          volumeMounts:
            - name: pvc-winesapos-repo
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: pvc-winesapos-repo
          persistentVolumeClaim:
            claimName: pvc-winesapos-repo
